<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="..\ExamRosterApp.Application\ExamRosterApp.Application.csproj" /><ProjectReference Include="..\ExamRosterApp.Domain\ExamRosterApp.Domain.csproj" /></ItemGroup><ItemGroup><PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" /><PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.8" /><PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8"><PrivateAssets>all</PrivateAssets></PackageReference></ItemGroup></Project>