<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWPF>true</UseWPF><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ExamRosterApp.Application\ExamRosterApp.Application.csproj" />
    <ProjectReference Include="..\ExamRosterApp.Infrastructure\ExamRosterApp.Infrastructure.csproj" />
  </ItemGroup>
</Project>
